pipeline {
    agent any
    tools {
        maven 'LocalMaven'
    }
    stages{
        stage('Build Application'){
            steps{
                sh 'mvn clean package'
            }
            post {
                success{
                    echo "Now Archiving the Artificats ..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}