pipeline {
    agent any
    tools {
        maven 'LocalMaven'
    }
    stages{
        stage('Build Application') {
            steps{
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success{
                    echo "Now Archiving the Artificats ..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy to Staging Environment') {
            steps{
                build job: 'Deploy_Application_Staging_Env'
            }
        }
    }
}